name: Deploy Vue app to GitHub Pages

# Trigger workflow on push to main or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger from Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Vue project
      - name: Build project
        run: npm run build

      # 5️⃣ Disable Jekyll (prevents GitHub Pages from processing the site)
      - name: Disable Jekyll
        run: touch dist/.nojekyll

      # 6️⃣ Deploy to gh-pages, force replacing everything
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true      # ✅ force replaces old content
          user_name: "github-actions"
          user_email: "github-actions@github.com"
